using System.Data;
using DKNet.EfCore.Specifications.Extensions;
using DKNet.EfCore.Specifications.Repositories;
using Minimal.AppServices.CustomerProfiles.V1.Events;
using Minimal.AppServices.CustomerProfiles.V1.Specs;

// ReSharper disable UnusedType.Global

namespace Minimal.AppServices.CustomerProfiles.V1.Actions;

/// <summary>
///     Command to create a new customer profile.
///     The <see cref="MembershipNo" /> is auto-generated by the membership provider when not supplied.
/// </summary>
[MapsFrom(typeof(CustomerProfile))]
public sealed record CreateProfileRequest : Fluents.Requests.IWitResponse<CustomerProfileDto>
{
    #region Properties

    /// <summary>
    ///     Gets or sets the identity of the acting user. Populated from the caller's claims — never settable by
    ///     the caller — via <see cref="FromClaimAttribute" />.
    /// </summary>
    [FromClaim(ClaimTypes.Name)]
    public string? ByUser { get; set; }

    /// <summary>
    /// Gets or sets the email address of the customer. This field is required and must be a valid email format.
    /// </summary>
    [Required]
    public string Email { get; set; } = null!;

    /// <summary>
    ///     Gets or sets the membership number. Optional; when not supplied it is auto-generated
    ///     by <see cref="IMembershipService" /> during command handling.
    ///     Marked <c>[JsonIgnore]</c> so clients cannot set it directly.
    /// </summary>
    [JsonIgnore]
    public string MembershipNo { get; set; } = null!;

    /// <summary>
    ///     Gets or sets the full name of the customer. Required; between 6 and 100 characters.
    /// </summary>
    [StringLength(150)]
    [Required]
    public string Name { get; set; } = null!;

    /// <summary>
    ///     Gets or sets the phone number of the customer. Must be a valid phone format; between 6 and 50 characters.
    /// </summary>
    [Phone]
    public string Phone { get; set; } = null!;

    #endregion
}

/// <summary>
///     FluentValidation validator for <see cref="CreateProfileRequest" />.
///     Enforces that <c>Email</c> is a valid e-mail address (max 1 000 chars),
///     <c>Phone</c> is between 6–50 characters, and <c>Name</c> is between 6–100 characters.
/// </summary>
internal sealed class CreateProfileCommandValidator : AbstractValidator<CreateProfileRequest>
{
    #region Constructors

    public CreateProfileCommandValidator()
    {
        RuleFor(a => a.Email).NotEmpty().EmailAddress().Length(1, 1000);
        RuleFor(a => a.Phone).NotEmpty().Length(6, 50);
        RuleFor(a => a.Name).NotEmpty().Length(6, 100);
    }

    #endregion
}

/// <summary>
///     Handles <see cref="CreateProfileRequest" /> by validating uniqueness, mapping the command to a
///     <see cref="CustomerProfile" /> entity, persisting it, and publishing a <see cref="ProfileCreatedEvent" />.
/// </summary>
/// <param name="repository">EF Core specification repository used for duplicate checking and persistence.</param>
/// <param name="membershipProvider">Service that generates the next membership number when one is not supplied.</param>
/// <param name="mapper">Mapster mapper used for entity mapping and lazy result projection.</param>
internal sealed class CreateProfileCommandHandler(
    IRepositorySpec repository,
    IMembershipService membershipProvider,
    IMapper mapper)
    : Fluents.Requests.IHandler<CreateProfileRequest, CustomerProfileDto>
{
    #region Methods

    /// <summary>
    ///     Processes the create-profile command.
    /// </summary>
    /// <remarks>
    ///     <list type="number">
    ///         <item>Generates a <c>MembershipNo</c> via <see cref="IMembershipService" /> when not already set.</item>
    ///         <item>Rejects the command with a failure result when the e-mail address is already in use.</item>
    ///         <item>Maps the command to a <see cref="CustomerProfile" /> entity and persists it.</item>
    ///         <item>
    ///             Raises a <see cref="ProfileCreatedEvent" /> and returns a lazy-mapped
    ///             <see cref="CustomerProfileDto" /> that resolves after <c>SaveChanges</c>.
    ///         </item>
    ///     </list>
    /// </remarks>
    /// <param name="request">The incoming create-profile command.</param>
    /// <param name="cancellationToken">Token to observe for cancellation requests.</param>
    /// <returns>
    ///     A successful <see cref="IResult{T}" /> containing the projected <see cref="CustomerProfileDto" />,
    ///     or a failed result when the e-mail already exists.
    /// </returns>
    /// <exception cref="NoNullAllowedException">
    ///     Thrown when <see cref="CustomerProfile.MembershipNo" /> is still empty after mapping,
    ///     indicating an unexpected mapping failure.
    /// </exception>
    public async Task<IResult<CustomerProfileDto>> OnHandle(
        CreateProfileRequest request,
        CancellationToken cancellationToken)
    {
        if (string.IsNullOrWhiteSpace(request.MembershipNo))
        {
            request.MembershipNo = await membershipProvider.NextValueAsync();
        }

        //Check duplicate
        if (await repository.AnyAsync(new SpecGetCustomerProfile(byEmail: request.Email),
                cancellationToken: cancellationToken))
        {
            return Result.Fail<CustomerProfileDto>($"Email {request.Email} is already existed.");
        }

        var profile = mapper.Map<CustomerProfile>(request);

        if (string.IsNullOrEmpty(profile.MembershipNo))
        {
            throw new NoNullAllowedException(nameof(profile.MembershipNo));
        }

        //Add
        await repository.AddAsync(profile, cancellationToken);

        //Event - Issue the Id maybe empty if the Id is generated by Database
        profile.AddEvent(new ProfileCreatedEvent(profile.Id, profile.Name));

        //NOTE this will return a lazy mapping result and only map profile to ProfileBasicView after SaveChanges is called.
        return mapper.ResultOf<CustomerProfileDto>(profile);
    }

    #endregion
}