// <auto-generated/>
#nullable enable
#pragma warning disable

namespace SlimBus.AppServices.Share.Generics
{
    partial class GenericListParametersPageQueryValidatorExtension
    {
        /// <remarks>
        /// Pattern:<br/>
        /// <code>^[A-Za-z_][A-Za-z0-9_]*(?:\\.[A-Za-z_][A-Za-z0-9_]*)*$</code><br/>
        /// Options:<br/>
        /// <code>RegexOptions.ExplicitCapture | RegexOptions.Compiled | RegexOptions.CultureInvariant</code><br/>
        /// Explanation:<br/>
        /// <code>
        /// ○ Match if at the beginning of the string.<br/>
        /// ○ Match a character in the set [A-Z_a-z].<br/>
        /// ○ Match a character in the set [0-9A-Z_a-z] greedily any number of times.<br/>
        /// ○ Loop greedily any number of times.<br/>
        ///     ○ Match '.'.<br/>
        ///     ○ Match a character in the set [A-Z_a-z].<br/>
        ///     ○ Match a character in the set [0-9A-Z_a-z] atomically any number of times.<br/>
        /// ○ Match if at the end of the string or if before an ending newline.<br/>
        /// </code>
        /// </remarks>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Text.RegularExpressions.Generator", "10.0.13.11305")]
        private static partial global::System.Text.RegularExpressions.Regex FieldNameValidationRegex() => global::System.Text.RegularExpressions.Generated.FieldNameValidationRegex_0.Instance;
    }
}

namespace SlimBus.AppServices.Share.Generics
{
    partial class GenericListParametersValidatorExtension
    {
        /// <remarks>
        /// Pattern:<br/>
        /// <code>^[A-Za-z_][A-Za-z0-9_]*(?:\\.[A-Za-z_][A-Za-z0-9_]*)*$</code><br/>
        /// Options:<br/>
        /// <code>RegexOptions.ExplicitCapture | RegexOptions.Compiled | RegexOptions.CultureInvariant</code><br/>
        /// Explanation:<br/>
        /// <code>
        /// ○ Match if at the beginning of the string.<br/>
        /// ○ Match a character in the set [A-Z_a-z].<br/>
        /// ○ Match a character in the set [0-9A-Z_a-z] greedily any number of times.<br/>
        /// ○ Loop greedily any number of times.<br/>
        ///     ○ Match '.'.<br/>
        ///     ○ Match a character in the set [A-Z_a-z].<br/>
        ///     ○ Match a character in the set [0-9A-Z_a-z] atomically any number of times.<br/>
        /// ○ Match if at the end of the string or if before an ending newline.<br/>
        /// </code>
        /// </remarks>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Text.RegularExpressions.Generator", "10.0.13.11305")]
        private static partial global::System.Text.RegularExpressions.Regex FieldNameValidationRegex() => global::System.Text.RegularExpressions.Generated.FieldNameValidationRegex_0.Instance;
    }
}

namespace System.Text.RegularExpressions.Generated
{
    using System;
    using System.Buffers;
    using System.CodeDom.Compiler;
    using System.Collections;
    using System.ComponentModel;
    using System.Globalization;
    using System.Runtime.CompilerServices;
    using System.Text.RegularExpressions;
    using System.Threading;

    /// <summary>Custom <see cref="Regex"/>-derived type for the FieldNameValidationRegex method.</summary>
    [GeneratedCodeAttribute("System.Text.RegularExpressions.Generator", "10.0.13.11305")]
    file sealed class FieldNameValidationRegex_0 : Regex
    {
        /// <summary>Cached, thread-safe singleton instance.</summary>
        internal static readonly FieldNameValidationRegex_0 Instance = new();
    
        /// <summary>Initializes the instance.</summary>
        private FieldNameValidationRegex_0()
        {
            base.pattern = "^[A-Za-z_][A-Za-z0-9_]*(?:\\.[A-Za-z_][A-Za-z0-9_]*)*$";
            base.roptions = RegexOptions.ExplicitCapture | RegexOptions.Compiled | RegexOptions.CultureInvariant;
            base.internalMatchTimeout = TimeSpan.FromMilliseconds(50);
            base.factory = new RunnerFactory();
            base.capsize = 1;
        }
            
        /// <summary>Provides a factory for creating <see cref="RegexRunner"/> instances to be used by methods on <see cref="Regex"/>.</summary>
        private sealed class RunnerFactory : RegexRunnerFactory
        {
            /// <summary>Creates an instance of a <see cref="RegexRunner"/> used by methods on <see cref="Regex"/>.</summary>
            protected override RegexRunner CreateInstance() => new Runner();
        
            /// <summary>Provides the runner that contains the custom logic implementing the specified regular expression.</summary>
            private sealed class Runner : RegexRunner
            {
                /// <summary>Scan the <paramref name="inputSpan"/> starting from base.runtextstart for the next match.</summary>
                /// <param name="inputSpan">The text being scanned by the regular expression.</param>
                protected override void Scan(ReadOnlySpan<char> inputSpan)
                {
                    // The pattern is anchored.  Validate the current position and try to match at it only.
                    if (TryFindNextPossibleStartingPosition(inputSpan) && !TryMatchAtCurrentPosition(inputSpan))
                    {
                        base.runtextpos = inputSpan.Length;
                    }
                }
        
                /// <summary>Search <paramref name="inputSpan"/> starting from base.runtextpos for the next location a match could possibly start.</summary>
                /// <param name="inputSpan">The text being scanned by the regular expression.</param>
                /// <returns>true if a possible match was found; false if no more matches are possible.</returns>
                private bool TryFindNextPossibleStartingPosition(ReadOnlySpan<char> inputSpan)
                {
                    int pos = base.runtextpos;
                    
                    // Empty matches aren't possible.
                    if ((uint)pos < (uint)inputSpan.Length)
                    {
                        // The pattern leads with a beginning (\A) anchor.
                        if (pos == 0)
                        {
                            return true;
                        }
                    }
                    
                    // No match found.
                    base.runtextpos = inputSpan.Length;
                    return false;
                }
        
                /// <summary>Determine whether <paramref name="inputSpan"/> at base.runtextpos is a match for the regular expression.</summary>
                /// <param name="inputSpan">The text being scanned by the regular expression.</param>
                /// <returns>true if the regular expression matches at the current position; otherwise, false.</returns>
                private bool TryMatchAtCurrentPosition(ReadOnlySpan<char> inputSpan)
                {
                    int pos = base.runtextpos;
                    int matchStart = pos;
                    int charloop_starting_pos = 0, charloop_ending_pos = 0;
                    int loop_iteration = 0;
                    int stackpos = 0;
                    ulong charMinusLowUInt64;
                    ReadOnlySpan<char> slice = inputSpan.Slice(pos);
                    
                    // Match if at the beginning of the string.
                    if (pos != 0)
                    {
                        return false; // The input didn't match.
                    }
                    
                    // Match a character in the set [A-Z_a-z].
                    if (slice.IsEmpty || ((long)((0xFFFFFFC2FFFFFFC0UL << (int)(charMinusLowUInt64 = (uint)slice[0] - 'A')) & (charMinusLowUInt64 - 64)) >= 0))
                    {
                        return false; // The input didn't match.
                    }
                    
                    // Match a character in the set [0-9A-Z_a-z] greedily any number of times.
                    //{
                        pos++;
                        slice = inputSpan.Slice(pos);
                        charloop_starting_pos = pos;
                        
                        int iteration = slice.IndexOfAnyExcept(Utilities.s_asciiWordChars);
                        if (iteration < 0)
                        {
                            iteration = slice.Length;
                        }
                        
                        slice = slice.Slice(iteration);
                        pos += iteration;
                        
                        charloop_ending_pos = pos;
                        goto CharLoopEnd;
                        
                        CharLoopBacktrack:
                        
                        base.CheckTimeout();
                        
                        if (charloop_starting_pos >= charloop_ending_pos)
                        {
                            return false; // The input didn't match.
                        }
                        pos = --charloop_ending_pos;
                        slice = inputSpan.Slice(pos);
                        
                        CharLoopEnd:
                    //}
                    
                    // Loop greedily any number of times.
                    //{
                        loop_iteration = 0;
                        
                        LoopBody:
                        Utilities.StackPush(ref base.runstack!, ref stackpos, pos);
                        
                        loop_iteration++;
                        
                        if ((uint)slice.Length < 2 ||
                            slice[0] != '.' || // Match '.'.
                            ((long)((0xFFFFFFC2FFFFFFC0UL << (int)(charMinusLowUInt64 = (uint)slice[1] - 'A')) & (charMinusLowUInt64 - 64)) >= 0)) // Match a character in the set [A-Z_a-z].
                        {
                            goto LoopIterationNoMatch;
                        }
                        
                        // Match a character in the set [0-9A-Z_a-z] atomically any number of times.
                        {
                            int iteration1 = slice.Slice(2).IndexOfAnyExcept(Utilities.s_asciiWordChars);
                            if (iteration1 < 0)
                            {
                                iteration1 = slice.Length - 2;
                            }
                            
                            slice = slice.Slice(iteration1);
                            pos += iteration1;
                        }
                        
                        pos += 2;
                        slice = inputSpan.Slice(pos);
                        
                        // The loop has no upper bound. Continue iterating greedily.
                        goto LoopBody;
                        
                        // The loop iteration failed. Put state back to the way it was before the iteration.
                        LoopIterationNoMatch:
                        if (--loop_iteration < 0)
                        {
                            // Unable to match the remainder of the expression after exhausting the loop.
                            goto CharLoopBacktrack;
                        }
                        pos = base.runstack![--stackpos];
                        slice = inputSpan.Slice(pos);
                        LoopEnd:;
                    //}
                    
                    // Match if at the end of the string or if before an ending newline.
                    if (pos < inputSpan.Length - 1 || ((uint)pos < (uint)inputSpan.Length && inputSpan[pos] != '\n'))
                    {
                        goto LoopIterationNoMatch;
                    }
                    
                    // The input matched.
                    base.runtextpos = pos;
                    base.Capture(0, matchStart, pos);
                    return true;
                }
            }
        }

    }
    
    /// <summary>Helper methods used by generated <see cref="Regex"/>-derived implementations.</summary>
    [GeneratedCodeAttribute("System.Text.RegularExpressions.Generator", "10.0.13.11305")]
    file static class Utilities
    {
        /// <summary>Pushes 1 value onto the backtracking stack.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        internal static void StackPush(ref int[] stack, ref int pos, int arg0)
        {
            // If there's space available for the value, store it.
            int[] s = stack;
            int p = pos;
            if ((uint)p < (uint)s.Length)
            {
                s[p] = arg0;
                pos++;
                return;
            }
        
            // Otherwise, resize the stack to make room and try again.
            WithResize(ref stack, ref pos, arg0);
        
            // <summary>Resize the backtracking stack array and push 1 value onto the stack.</summary>
            [MethodImpl(MethodImplOptions.NoInlining)]
            static void WithResize(ref int[] stack, ref int pos, int arg0)
            {
                Array.Resize(ref stack, (pos + 0) * 2);
                StackPush(ref stack, ref pos, arg0);
            }
        }
        
        /// <summary>Supports searching for characters in or not in "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ_abcdefghijklmnopqrstuvwxyz".</summary>
        internal static readonly SearchValues<char> s_asciiWordChars = SearchValues.Create("0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ_abcdefghijklmnopqrstuvwxyz");
    }
}
