using SlimBus.Domains.Features.CustomerProfiles.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace SlimBus.Infra.Features.CustomerProfiles.Mappers;

/// <summary>
/// EF Core mapper configuration for CustomerProfile entity.
/// 
/// This mapper demonstrates:
/// - Auto-discovery by Scrutor (sealed class, in Mappers/ folder)
/// - Property configuration with validation (lengths, nullability)
/// - Relationship configuration (foreign keys)
/// - Index configuration for query performance
/// - Schema organization (schemas for different concerns)
/// 
/// Applied automatically via UseAutoConfigModel in InfraSetup.
/// </summary>
public sealed class CustomerProfileMapper : IEntityTypeConfiguration<CustomerProfile>
{
    public void Configure(EntityTypeBuilder<CustomerProfile> builder)
    {
        // ============ TABLE SETUP ============
        // Organize related entities in "customers" schema
        // Table name matches entity name by convention
        builder.ToTable("CustomerProfiles", "customers");

        // ============ PRIMARY KEY ============
        // Id is the primary key (GUID generated externally, not by database)
        builder.HasKey(x => x.Id);

        // ============ PROPERTY MAPPING ============
        
        // Id property - GUID, required, not generated by database
        builder.Property(x => x.Id)
            .ValueGeneratedNever()  // Application generates the ID
            .IsRequired();

        // UserId - GUID, required (foreign key to Users table)
        builder.Property(x => x.UserId)
            .IsRequired();

        // FullName - string, max 200 chars, required
        // This length matches business rule: customer names are at most 200 characters
        builder.Property(x => x.FullName)
            .HasMaxLength(200)
            .IsRequired();

        // Email - string, max 256 chars, required
        // Standard email max length is 256 characters (per RFC)
        builder.Property(x => x.Email)
            .HasMaxLength(256)
            .IsRequired();

        // DateOfBirth - nullable DateTime, optional
        // IsRequired(false) means NULL is allowed when not provided
        builder.Property(x => x.DateOfBirth)
            .IsRequired(false);

        // CreatedAt - DateTime, required, set once at creation
        builder.Property(x => x.CreatedAt)
            .IsRequired();

        // UpdatedAt - DateTime, required, modified on every update
        builder.Property(x => x.UpdatedAt)
            .IsRequired();

        // ============ INDEXES FOR QUERY PERFORMANCE ============
        
        // Index on UserId - common query: "find profiles for this user"
        builder.HasIndex(x => x.UserId)
            .HasDatabaseName("IX_CustomerProfiles_UserId");

        // UNIQUE index on Email - business rule: each customer email is unique
        // Prevents duplicate email addresses at the database level
        builder.HasIndex(x => x.Email)
            .HasDatabaseName("IX_CustomerProfiles_Email")
            .IsUnique();

        // Index on CreatedAt - common query: "find profiles created on/after date"
        builder.HasIndex(x => x.CreatedAt)
            .HasDatabaseName("IX_CustomerProfiles_CreatedAt");

        // Composite index for pagination: find profiles by user, ordered by creation date
        // This supports query: "get pages of profiles for user X, paginated by created date"
        builder.HasIndex(x => new { x.UserId, x.CreatedAt })
            .HasDatabaseName("IX_CustomerProfiles_UserId_CreatedAt");
    }
}
