<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <LangVersion>default</LangVersion>
        <ImplicitUsings>true</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="DKNet.EfCore.Abstractions"/>
        <PackageReference Include="DKNet.EfCore.DataAuthorization"/>
        <PackageReference Include="DKNet.EfCore.DtoGenerator">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Update="Meziantou.Analyzer">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Minimal.Share\Minimal.Share.csproj" />
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="Minimal.App.Tests"/>
        <InternalsVisibleTo Include="Minimal.Infra"/>
    </ItemGroup>
</Project>