name: Build and Publish NuGet Package

'on':
  workflow_dispatch:
  push:
    branches:
      - dev
      - main

permissions:
  contents: write
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      # Versioning
      - name: Calculate version
        id: version
        uses: paulhatch/semantic-version@v5.4.0
        with:
          tag_prefix: "v"
          major_pattern: "(MAJOR)"
          minor_pattern: "(MINOR)"
          version_format: "${major}.${minor}.${patch}"
          bump_each_commit: false
          search_commit_body: false

      - name: Print the version
        run: echo ${{ steps.version.outputs.version }}
    
    # Dotnet build and publish
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.0.x"

      - name: Restore
        run: dotnet restore src/DKNet.Templates.sln

      - name: Build
        run: dotnet build src/DKNet.Templates.sln -c Release --no-restore

    #   - name: Test
    #     run: dotnet test src/DKNet.Templates.sln --settings src/coverage.runsettings --collect:"XPlat Code Coverage" --no-build

      - name: Set nuspec version
        run: |
          sed -i.bak "s|<version>.*</version>|<version>${{ steps.version.outputs.version }}</version>|" src/DKNet.Minimal.Template.nuspec
          rm src/DKNet.Minimal.Template.nuspec.bak

      - name: Pack template
        run: dotnet pack src/DKNet.Minimal.Template.csproj -c Release -o src/nupkgs

      - name: Add GitHub Packages source
        run: |
          dotnet nuget add source \
            --username "${{ github.actor }}" \
            --password "${{ secrets.GITHUB_TOKEN }}" \
            --store-password-in-clear-text \
            --name "github" \
            "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"

      - name: Push package to GitHub Packages
        run: |
          dotnet nuget push "src/nupkgs/*.nupkg" \
            --source "github" \
            --api-key "${{ secrets.GITHUB_TOKEN }}" \
            --skip-duplicate
    
    # Create Release
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          make_latest: true
          #files: ${{ runner.WORKSPACE }}/nupkgs/release.zip
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: v${{ steps.version.outputs.version }}
